-- Script để kiểm tra cấu trúc bảng trong SQL Server

-- 1. Kiểm tra cấu trúc bảng classrooms
SELECT 'CLASSROOMS_STRUCTURE' as check_type;
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE,
    COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'classrooms'
ORDER BY ORDINAL_POSITION;

-- 2. Kiểm tra cấu trúc bảng users
SELECT 'USERS_STRUCTURE' as check_type;
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE,
    COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'users'
ORDER BY ORDINAL_POSITION;

-- 3. Kiểm tra cấu trúc bảng assignments
SELECT 'ASSIGNMENTS_STRUCTURE' as check_type;
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE,
    COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'assignments'
ORDER BY ORDINAL_POSITION;

-- 4. Kiểm tra cấu trúc bảng submissions
SELECT 'SUBMISSIONS_STRUCTURE' as check_type;
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE,
    COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'submissions'
ORDER BY ORDINAL_POSITION;

-- 5. Kiểm tra cấu trúc bảng classroom_enrollments
SELECT 'CLASSROOM_ENROLLMENTS_STRUCTURE' as check_type;
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE,
    COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'classroom_enrollments'
ORDER BY ORDINAL_POSITION;

-- 6. Liệt kê tất cả các bảng trong database
SELECT 'ALL_TABLES' as check_type;
SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_NAME;
