-- =========================================================
-- Auto-loaded Sample Data for MVS Course Enrollment System
-- This file will be automatically executed by Spring Boot on startup
-- when using spring.jpa.hibernate.ddl-auto=create-drop
-- =========================================================

-- Insert sample public course templates (đổi sang các môn cấp 3: Toán, Lý, Hóa, Văn, Anh, Sinh)
INSERT INTO course_templates (
    name, 
    description, 
    subject, 
    total_weeks, 
    is_public, 
    is_active, 
    enrollment_fee, 
    max_students_per_template, 
    status, 
    created_at, 
    updated_at
) VALUES 
-- Programming Courses
('Luyện thi THPT Quốc gia - Toán', 
 'Khóa luyện thi môn Toán dành cho học sinh cấp 3, bao quát Đại số, Hình học, Giải tích với hệ thống bài tập theo chuyên đề và đề thi thử.', 
 'Toán', 
 12, 
 1, 
 1, 
 2500000.00, 
 30, 
 'ACTIVE', 
 GETDATE(), 
 GETDATE()),

('Vật lý Nâng cao 11-12', 
 'Ôn tập và nâng cao kiến thức Vật lý cấp 3: Cơ học, Điện học, Quang học, Hạt nhân; bám sát chương trình và luyện đề.', 
 'Vật lý', 
 10, 
 1, 
 1, 
 3200000.00, 
 25, 
 'ACTIVE', 
 GETDATE(), 
 GETDATE()),

('Hóa học Hữu cơ - Vô cơ trọng tâm', 
 'Hệ thống hóa kiến thức Hóa học 10-12, chú trọng bài tập vô cơ, hữu cơ và các dạng đồ thị, trắc nghiệm tính nhanh.', 
 'Hóa học', 
 16, 
 1, 
 1, 
 4500000.00, 
 20, 
 'ACTIVE', 
 GETDATE(), 
 GETDATE()),

-- Business & Marketing Courses
('Ngữ văn 10-12 - Đọc hiểu & Nghị luận', 
 'Ôn tập tác phẩm trọng tâm, kỹ năng đọc hiểu và nghị luận xã hội/văn học; phương pháp làm bài đạt điểm cao.', 
 'Ngữ văn', 
 8, 
 1, 
 1, 
 1800000.00, 
 35, 
 'ACTIVE', 
 GETDATE(), 
 GETDATE()),

('Tiếng Anh - Ngữ pháp & Từ vựng', 
 'Củng cố ngữ pháp, từ vựng, kỹ năng đọc hiểu/viết/Nghe nói cho học sinh cấp 3, kèm đề thi THPTQG.', 
 'Tiếng Anh', 
 14, 
 1, 
 1, 
 3800000.00, 
 18, 
 'ACTIVE', 
 GETDATE(), 
 GETDATE()),

-- Language Courses
('Sinh học - Di truyền và Tiến hóa', 
 'Chuyên đề Sinh học 12: Di truyền học, Biến dị, Tiến hóa, Sinh thái; phù hợp ôn thi đại học.', 
 'Sinh học', 
 10, 
 1, 
 1, 
 1500000.00, 
 40, 
 'ACTIVE', 
 GETDATE(), 
 GETDATE()),

('Tiếng Anh Chuyên đề - Reading & Grammar', 
 'Chuyên đề luyện Reading, Grammar dành cho cấp 3, tăng tốc điểm số nhanh trước kỳ thi.', 
 'Tiếng Anh', 
 12, 
 1, 
 1, 
 2200000.00, 
 25, 
 'ACTIVE', 
 GETDATE(), 
 GETDATE()),

-- Design & Creative Courses
('Toán Hình học Nâng cao', 
 'Chuyên sâu Hình học không gian, tọa độ, vector; mẹo giải nhanh trắc nghiệm.', 
 'Toán', 
 11, 
 1, 
 1, 
 2800000.00, 
 20, 
 'ACTIVE', 
 GETDATE(), 
 GETDATE()),

('Vật lý - Điện xoay chiều & Dao động', 
 'Trọng tâm dao động, sóng, điện xoay chiều; các dạng bài hay gặp trong đề thi.', 
 'Vật lý', 
 6, 
 1, 
 1, 
 1200000.00, 
 30, 
 'ACTIVE', 
 GETDATE(), 
 GETDATE()),

-- Free Courses
('Ôn tập Tổng hợp Toán 12 (Free)', 
 'Khóa miễn phí gồm các đề tổng hợp và chữa chi tiết nhằm củng cố toàn bộ kiến thức Toán 12.', 
 'Toán', 
 8, 
 1, 
 1, 
 0.00, 
 50, 
 'ACTIVE', 
 GETDATE(), 
 GETDATE()),

('Ôn tập Tiếng Anh 12 (Free)', 
 'Tổng hợp chuyên đề Ngữ pháp và Đọc hiểu trọng tâm cho học sinh lớp 12.', 
 'Tiếng Anh', 
 6, 
 1, 
 1, 
 0.00, 
 100, 
 'ACTIVE', 
 GETDATE(), 
 GETDATE()),

-- Advanced Courses
('Chuyên đề Hóa vô cơ nâng cao', 
 'Các dạng bài vô cơ khó, phương pháp quy đổi, bảo toàn điện tích/khối lượng; luyện đề nâng cao.', 
 'Hóa học', 
 20, 
 1, 
 1, 
 5500000.00, 
 15, 
 'ACTIVE', 
 GETDATE(), 
 GETDATE()),

('Sinh học - Sinh thái học nâng cao', 
 'Chuyên sâu hệ sinh thái, quần xã, dòng năng lượng; bài tập tổng hợp.', 
 'Sinh học', 
 18, 
 1, 
 1, 
 6200000.00, 
 12, 
 'ACTIVE', 
 GETDATE(), 
 GETDATE()),

-- Professional Development
('Ngữ văn - Tuyển tập nghị luận hay', 
 'Tuyển tập đề nghị luận xã hội/văn học có dàn ý và bài mẫu chất lượng.', 
 'Ngữ văn', 
 14, 
 1, 
 1, 
 3500000.00, 
 25, 
 'ACTIVE', 
 GETDATE(), 
 GETDATE()),

('Tiếng Anh - Luyện đề tổng hợp', 
 'Bộ đề tổng hợp theo chuyên đề và theo đề thi chuẩn, kèm chữa chi tiết.', 
 'Tiếng Anh', 
 12, 
 1, 
 1, 
 4200000.00, 
 20, 
 'ACTIVE', 
 GETDATE(), 
 GETDATE());