-- =========================================================
-- Auto-loaded Sample Data for MVS Course Enrollment System
-- This file will be automatically executed by Spring Boot on startup
-- when using spring.jpa.hibernate.ddl-auto=create-drop
-- =========================================================

-- Insert sample public course templates
INSERT INTO course_templates (
    name, 
    description, 
    subject, 
    total_weeks, 
    is_public, 
    is_active, 
    enrollment_fee, 
    max_students_per_template, 
    status, 
    created_at, 
    updated_at
) VALUES 
-- Programming Courses
('Introduction to Web Development', 
 'Learn the fundamentals of web development including HTML5, CSS3, and JavaScript. Perfect for beginners who want to start their journey in web development. You will build real projects and learn modern development practices.', 
 'Programming', 
 12, 
 1, 
 1, 
 2500000.00, 
 30, 
 'ACTIVE', 
 GETDATE(), 
 GETDATE()),

('React.js for Beginners', 
 'Master React.js, the most popular JavaScript library for building user interfaces. Learn components, hooks, state management, and build a complete web application from scratch.', 
 'Programming', 
 10, 
 1, 
 1, 
 3200000.00, 
 25, 
 'ACTIVE', 
 GETDATE(), 
 GETDATE()),

('Python Programming Bootcamp', 
 'Comprehensive Python course covering basics to advanced topics. Learn data structures, OOP, web development with Django, and data analysis. Includes hands-on projects and career guidance.', 
 'Programming', 
 16, 
 1, 
 1, 
 4500000.00, 
 20, 
 'ACTIVE', 
 GETDATE(), 
 GETDATE()),

-- Business & Marketing Courses
('Digital Marketing Mastery', 
 'Complete digital marketing course covering social media marketing, SEO, Google Ads, content marketing, and analytics. Learn to create effective marketing campaigns that drive results.', 
 'Marketing', 
 8, 
 1, 
 1, 
 1800000.00, 
 35, 
 'ACTIVE', 
 GETDATE(), 
 GETDATE()),

('Data Science with Python', 
 'Learn data science from scratch using Python. Cover pandas, numpy, matplotlib, machine learning basics, and work with real datasets. Perfect for career transition into data science.', 
 'Data Science', 
 14, 
 1, 
 1, 
 3800000.00, 
 18, 
 'ACTIVE', 
 GETDATE(), 
 GETDATE()),

-- Language Courses
('Business English Communication', 
 'Improve your English communication skills for professional environments. Focus on business writing, presentations, meetings, and email communication. Includes practice sessions and feedback.', 
 'Language', 
 10, 
 1, 
 1, 
 1500000.00, 
 40, 
 'ACTIVE', 
 GETDATE(), 
 GETDATE()),

('IELTS Preparation Course', 
 'Comprehensive IELTS preparation covering all four skills: Reading, Writing, Listening, and Speaking. Includes practice tests, strategies, and personalized feedback to achieve your target score.', 
 'Language', 
 12, 
 1, 
 1, 
 2200000.00, 
 25, 
 'ACTIVE', 
 GETDATE(), 
 GETDATE()),

-- Design & Creative Courses
('UI/UX Design Fundamentals', 
 'Learn user interface and user experience design principles. Master Figma, create wireframes, prototypes, and design systems. Build a professional portfolio with real client projects.', 
 'Design', 
 11, 
 1, 
 1, 
 2800000.00, 
 20, 
 'ACTIVE', 
 GETDATE(), 
 GETDATE()),

('Photography for Beginners', 
 'Master photography basics including composition, lighting, camera settings, and post-processing. Learn to take professional-quality photos with any camera, including smartphones.', 
 'Photography', 
 6, 
 1, 
 1, 
 1200000.00, 
 30, 
 'ACTIVE', 
 GETDATE(), 
 GETDATE()),

-- Free Courses
('Introduction to Computer Science', 
 'Free introductory course to computer science concepts. Learn programming logic, algorithms, and basic computer systems. Perfect starting point for anyone interested in technology.', 
 'Computer Science', 
 8, 
 1, 
 1, 
 0.00, 
 50, 
 'ACTIVE', 
 GETDATE(), 
 GETDATE()),

('Personal Finance Management', 
 'Free course on managing personal finances. Learn budgeting, saving, investing basics, and financial planning. Build a solid foundation for financial independence.', 
 'Finance', 
 6, 
 1, 
 1, 
 0.00, 
 100, 
 'ACTIVE', 
 GETDATE(), 
 GETDATE()),

-- Advanced Courses
('Full-Stack JavaScript Development', 
 'Advanced course covering both frontend and backend development with JavaScript. Learn Node.js, Express, MongoDB, React, and deploy full-stack applications to the cloud.', 
 'Programming', 
 20, 
 1, 
 1, 
 5500000.00, 
 15, 
 'ACTIVE', 
 GETDATE(), 
 GETDATE()),

('Machine Learning with TensorFlow', 
 'Advanced machine learning course using TensorFlow. Learn neural networks, deep learning, computer vision, and natural language processing. Includes real-world ML projects.', 
 'Data Science', 
 18, 
 1, 
 1, 
 6200000.00, 
 12, 
 'ACTIVE', 
 GETDATE(), 
 GETDATE()),

-- Professional Development
('Project Management Professional', 
 'Comprehensive project management course preparing you for PMP certification. Learn project planning, execution, monitoring, and closure using industry best practices.', 
 'Management', 
 14, 
 1, 
 1, 
 3500000.00, 
 25, 
 'ACTIVE', 
 GETDATE(), 
 GETDATE()),

('Cybersecurity Fundamentals', 
 'Essential cybersecurity course covering network security, ethical hacking, risk assessment, and security frameworks. Perfect for IT professionals and career changers.', 
 'Security', 
 12, 
 1, 
 1, 
 4200000.00, 
 20, 
 'ACTIVE', 
 GETDATE(), 
 GETDATE());