package com.classroomapp.classroombackend.repository.hrmanagement;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import com.classroomapp.classroombackend.model.hrmanagement.PayrollRecord;

/**
 * Repository interface for PayrollRecord entity
 */
@Repository
public interface PayrollRecordRepository extends JpaRepository<PayrollRecord, Long> {
    
    /**
     * Find payroll record by staff and period
     * @param staffId the staff ID
     * @param periodStart the period start date
     * @param periodEnd the period end date
     * @return optional payroll record
     */
    Optional<PayrollRecord> findByStaffIdAndPayPeriodStartAndPayPeriodEnd(
        Long staffId, LocalDate periodStart, LocalDate periodEnd);
    
    /**
     * Find payroll records by staff ID
     * @param staffId the staff ID
     * @param pageable pagination parameters
     * @return page of payroll records
     */
    Page<PayrollRecord> findByStaffIdOrderByPayPeriodStartDesc(Long staffId, Pageable pageable);
    
    /**
     * Find payroll records by staff ID (list)
     * @param staffId the staff ID
     * @return list of payroll records
     */
    List<PayrollRecord> findByStaffIdOrderByPayPeriodStartDesc(Long staffId);
    
    /**
     * Find payroll records by status
     * @param status the payroll status
     * @param pageable pagination parameters
     * @return page of payroll records
     */
    Page<PayrollRecord> findByStatusOrderByGeneratedAtDesc(PayrollRecord.PayrollStatus status, Pageable pageable);
    
    /**
     * Find payroll records by status (list)
     * @param status the payroll status
     * @return list of payroll records
     */
    List<PayrollRecord> findByStatusOrderByGeneratedAtDesc(PayrollRecord.PayrollStatus status);
    
    /**
     * Find payroll records by period
     * @param startDate the period start date
     * @param endDate the period end date
     * @param pageable pagination parameters
     * @return page of payroll records
     */
    Page<PayrollRecord> findByPayPeriodStartGreaterThanEqualAndPayPeriodEndLessThanEqualOrderByGeneratedAtDesc(
        LocalDate startDate, LocalDate endDate, Pageable pageable);
    
    /**
     * Find payroll records by period (list)
     * @param startDate the period start date
     * @param endDate the period end date
     * @return list of payroll records
     */
    List<PayrollRecord> findByPayPeriodStartGreaterThanEqualAndPayPeriodEndLessThanEqualOrderByGeneratedAtDesc(
        LocalDate startDate, LocalDate endDate);
    
    /**
     * Find payroll records generated by specific user
     * @param generatedBy the user ID who generated
     * @return list of payroll records
     */
    List<PayrollRecord> findByGeneratedByIdOrderByGeneratedAtDesc(Long generatedBy);
    
    /**
     * Check if payroll exists for staff and period
     * @param staffId the staff ID
     * @param periodStart the period start date
     * @param periodEnd the period end date
     * @return true if exists
     */
    boolean existsByStaffIdAndPayPeriodStartAndPayPeriodEnd(
        Long staffId, LocalDate periodStart, LocalDate periodEnd);
    
    /**
     * Count payroll records by status
     * @param status the payroll status
     * @return count of records
     */
    long countByStatus(PayrollRecord.PayrollStatus status);
    
    /**
     * Count payroll records by staff
     * @param staffId the staff ID
     * @return count of records
     */
    long countByStaffId(Long staffId);
    
    /**
     * Find recent payroll records
     * @param days number of days to look back
     * @return list of recent payroll records
     */
    @Query("SELECT pr FROM PayrollRecord pr " +
           "WHERE pr.generatedAt >= :since " +
           "ORDER BY pr.generatedAt DESC")
    List<PayrollRecord> findRecentPayrollRecords(@Param("since") LocalDateTime since);
    
    /**
     * Find staff payroll history
     * @param staffId the staff ID
     * @param months number of months to look back
     * @return list of payroll records
     */
    @Query("SELECT pr FROM PayrollRecord pr " +
           "WHERE pr.staff.id = :staffId " +
           "AND pr.payPeriodStart >= :since " +
           "ORDER BY pr.payPeriodStart DESC")
    List<PayrollRecord> findStaffPayrollHistory(@Param("staffId") Long staffId, 
                                               @Param("since") LocalDate since);
    
    /**
     * Get payroll summary statistics
     * @param periodStart the period start date
     * @param periodEnd the period end date
     * @return payroll summary data
     */
    @Query("SELECT " +
           "COUNT(pr) as totalRecords, " +
           "COALESCE(SUM(pr.grossPay), 0) as totalGrossPay, " +
           "COALESCE(SUM(pr.netPay), 0) as totalNetPay, " +
           "COALESCE(SUM(pr.totalDeductions), 0) as totalDeductions, " +
           "COALESCE(SUM(pr.totalWorkingHours), 0) as totalWorkingHours " +
           "FROM PayrollRecord pr " +
           "WHERE pr.payPeriodStart >= :periodStart " +
           "AND pr.payPeriodEnd <= :periodEnd")
    Object[] getPayrollSummary(@Param("periodStart") LocalDate periodStart, 
                              @Param("periodEnd") LocalDate periodEnd);
    
    /**
     * Get payroll statistics by status
     * @param periodStart the period start date
     * @param periodEnd the period end date
     * @return status statistics
     */
    @Query("SELECT pr.status, COUNT(pr) " +
           "FROM PayrollRecord pr " +
           "WHERE pr.payPeriodStart >= :periodStart " +
           "AND pr.payPeriodEnd <= :periodEnd " +
           "GROUP BY pr.status")
    List<Object[]> getPayrollStatusStatistics(@Param("periodStart") LocalDate periodStart, 
                                             @Param("periodEnd") LocalDate periodEnd);
    
    /**
     * Find pending payroll records (draft or processed)
     * @return list of pending records
     */
    @Query("SELECT pr FROM PayrollRecord pr " +
           "WHERE pr.status IN ('DRAFT', 'PROCESSED') " +
           "ORDER BY pr.payPeriodEnd ASC")
    List<PayrollRecord> findPendingPayrollRecords();
    
    /**
     * Find overdue payroll records
     * @param cutoffDate the cutoff date
     * @return list of overdue records
     */
    @Query("SELECT pr FROM PayrollRecord pr " +
           "WHERE pr.status IN ('DRAFT', 'PROCESSED') " +
           "AND pr.payPeriodEnd < :cutoffDate " +
           "ORDER BY pr.payPeriodEnd ASC")
    List<PayrollRecord> findOverduePayrollRecords(@Param("cutoffDate") LocalDate cutoffDate);
    
    /**
     * Find payroll records by staff and status
     * @param staffId the staff ID
     * @param status the payroll status
     * @return list of payroll records
     */
    List<PayrollRecord> findByStaffIdAndStatusOrderByPayPeriodStartDesc(
        Long staffId, PayrollRecord.PayrollStatus status);
    
    /**
     * Get monthly payroll statistics
     * @param year the year
     * @param month the month (1-12)
     * @return monthly statistics
     */
    @Query("SELECT " +
           "COUNT(DISTINCT pr.staff.id) as totalStaff, " +
           "COALESCE(SUM(pr.grossPay), 0) as totalGrossPay, " +
           "COALESCE(SUM(pr.netPay), 0) as totalNetPay, " +
           "COALESCE(SUM(pr.totalDeductions), 0) as totalDeductions, " +
           "COALESCE(AVG(pr.grossPay), 0) as averageGrossPay, " +
           "COALESCE(AVG(pr.netPay), 0) as averageNetPay, " +
           "COALESCE(SUM(pr.totalWorkingHours), 0) as totalWorkingHours, " +
           "COALESCE(AVG(pr.totalWorkingHours), 0) as averageWorkingHours " +
           "FROM PayrollRecord pr " +
           "WHERE YEAR(pr.payPeriodStart) = :year " +
           "AND MONTH(pr.payPeriodStart) = :month")
    Object[] getMonthlyPayrollStatistics(@Param("year") int year, @Param("month") int month);
    
    /**
     * Find payroll records with high deductions
     * @param thresholdPercentage the threshold percentage (e.g., 20 for 20%)
     * @return list of records with high deductions
     */
    @Query("SELECT pr FROM PayrollRecord pr " +
           "WHERE pr.grossPay > 0 " +
           "AND (pr.totalDeductions / pr.grossPay * 100) > :thresholdPercentage " +
           "ORDER BY (pr.totalDeductions / pr.grossPay) DESC")
    List<PayrollRecord> findPayrollRecordsWithHighDeductions(@Param("thresholdPercentage") BigDecimal thresholdPercentage);
    
    /**
     * Delete old payroll records (for archival)
     * @param cutoffDate the cutoff date
     * @return number of deleted records
     */
    @Query("DELETE FROM PayrollRecord pr " +
           "WHERE pr.status = 'PAID' " +
           "AND pr.paidAt < :cutoffDate")
    int deleteOldPayrollRecords(@Param("cutoffDate") LocalDateTime cutoffDate);
    
    /**
     * Find duplicate payroll records (same staff and period)
     * @return list of duplicate records
     */
    @Query("SELECT pr FROM PayrollRecord pr " +
           "WHERE EXISTS (" +
           "    SELECT pr2 FROM PayrollRecord pr2 " +
           "    WHERE pr2.staff.id = pr.staff.id " +
           "    AND pr2.payPeriodStart = pr.payPeriodStart " +
           "    AND pr2.payPeriodEnd = pr.payPeriodEnd " +
           "    AND pr2.id != pr.id" +
           ") " +
           "ORDER BY pr.staff.id, pr.payPeriodStart")
    List<PayrollRecord> findDuplicatePayrollRecords();
}