package com.classroomapp.classroombackend.dto;

import java.time.LocalDate;

import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class CloneClassRequest {
    
    @NotBlank(message = "New class name is required")
    private String newClassName;
    
    private Long newTeacherId;
    
    private Long newRoomId;
    
    private LocalDate newStartDate;
    
    private LocalDate newEndDate;
    
    private String newSchedule;
    
    private Long createdBy;
    
    // Getters and setters are auto-generated by Lombok @Data
    // But if you need them explicitly:
    
    public String getNewClassName() {
        return newClassName;
    }
    
    public void setNewClassName(String newClassName) {
        this.newClassName = newClassName;
    }
    
    public Long getNewTeacherId() {
        return newTeacherId;
    }
    
    public void setNewTeacherId(Long newTeacherId) {
        this.newTeacherId = newTeacherId;
    }
    
    public Long getNewRoomId() {
        return newRoomId;
    }
    
    public void setNewRoomId(Long newRoomId) {
        this.newRoomId = newRoomId;
    }
    
    public LocalDate getNewStartDate() {
        return newStartDate;
    }
    
    public void setNewStartDate(LocalDate newStartDate) {
        this.newStartDate = newStartDate;
    }
    
    public LocalDate getNewEndDate() {
        return newEndDate;
    }
    
    public void setNewEndDate(LocalDate newEndDate) {
        this.newEndDate = newEndDate;
    }
    
    public String getNewSchedule() {
        return newSchedule;
    }
    
    public void setNewSchedule(String newSchedule) {
        this.newSchedule = newSchedule;
    }
    
    public Long getCreatedBy() {
        return createdBy;
    }
    
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }
}